### ISSUE TITLE
Move checklist and recommendation to this repo

### ISSUE THREAD

**Issue by malvikasharan** [galaxy-carpentries/gallantries-extras#1]
Link: [https://github.com/galaxy-carpentries/gallantries/tree/master/extras](https://github.com/galaxy-carpentries/gallantries/tree/master/extras)

- [x] Move planning checklist by creating a landing page and splitting the checklist by oganisers, instructors and helpers

- [ ] Move recommendations

- [ ] Link it to the main Gallantries page

- [ ] In the future, think about directly displaying it on the Gallantries page
